# Generated by Django 4.1.5 on 2023-01-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255)),
                ('varsta', models.IntegerField()),
                ('specie', models.CharField(max_length=255)),
                ('proprietar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proprietar')),
            ],
        ),
    ]
